server:
  port: 8080
localstack:
  uri: http://localhost:4566
  bucketName: resources-bucket

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resources
    username: admin
    password: admin1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB